[package]
name = "DaddyBird"
version = "0.1.0"
edition = "2021"

[dependencies]
bracket-lib = { version = "~0.8.7", default-features = false, features = ["opengl", "serde"] }

[patch.crates-io]
freetype-rs = { path = "vendor/freetype-rs" }
